### ISSUE TITLE
GradientImage example has style issues

### ISSUE THREAD

**Issue by ctrueden** [imagej/tutorials#10]
In the tutorial code we have a simple command example. It creates a GradientImage. However the code example uses bad style in that it is somewhat dependent upon the expectation that the created Img is backed by PlanarAccess. It uses setPlane(). This is to show users that they can ignore our generic types. But for the June 2013 beta release (beta 7) we are thinking that the Img creating/opening code will work in CellImgs depending upon the size of the Img. So we shouldn't encourage users to rely on setPlane(). Or we need to change its contract.

Migrated-From: http://trac.imagej.net/ticket/1850

**Comment by stelfrich** [comment]
I will take care of this when `RichImg` (or whatever it may be called)/`ImgPlus`/`Dataset` has settled.

Should we already introduce _Ops_ for creating images in this tutorial?

**Comment by ctrueden** [comment]
This is technically still an issue. But it will become moot soon, because the `simple-commands` tutorial is going away in favor of Beaker notebooks, which do not use the undesirable `Dataset` API. Closing preemptively, since no further action will be required to solve this later.
