### ISSUE TITLE
Fix ExecuteCommands to work with fake format changes

### ISSUE THREAD

**Issue by hinerm** [imagej/tutorials#101]
`ExecuteCommand` currently works by calling the [OpenFile](https://github.com/scijava/scijava-plugins-commands/blob/c1fbbd44a240213b748ef005afc478b9bbbf291d/src/main/java/org/scijava/plugins/commands/io/OpenFile.java#L83-L84) commands with [a `.fake`](https://github.com/imagej/tutorials/blob/62f5280f5f38fd9e5f3485f7aa632d9b052de8c4/java/execute-commands/src/main/java/ExecuteCommands.java#L192) image. This `.fake` format is not supported with the current `OpenFile` implementation.

Using the latest pom-scijava, test:
* Does the current [scijava-plugins-commands](https://github.com/scijava/scijava-plugins-commands) fix the issue via [this commit](https://github.com/scijava/scijava-plugins-commands/commit/ffb84ad783d36221779795f4a8f5cf0316f213ff)?

If it does, great, let me know. If not we'll have to discuss other options.

**Comment by ecmagnuson** [comment]
The commit has not resolved the problem.

Error thrown:
[ERROR] java.io.FileNotFoundException: sample-image.fake (No such file or directory)

This is the same error when using "scifiotestimg" extension as well.

**Comment by hinerm** [comment]
>The commit has not resolved the problem.

@ecmagnuson Yeah I'm not surprised. It forces a `FileLocation` which is not a [TestImgLocation](https://github.com/scifio/scifio/blob/9d9e56e46d747d9a7b9ad78000057f512bfb15e0/src/main/java/io/scif/io/location/TestImgLocation.java).

>I'm still not fully certain, but SCIFIO has it's own fake File types, right - i.e it picks up on ".fake"?

Yep! It has this [TestImgLocationResolver](https://github.com/scifio/scifio/blob/9d9e56e46d747d9a7b9ad78000057f512bfb15e0/src/main/java/io/scif/io/location/TestImgLocationResolver.java#L63) which picks up on the `.fake`.

So there's a question: does `OpenFile` have to strictly imply `FileLocation`? I think not. I can imagine other scenarios like this `.fake` situation where a "file" on disk represents some non-file scheme for opening something.

`TestImgLocationResolver` is a `Resolver` plugin that gets picked up when... resolving the location! To do this we use the [LocationService](https://github.com/scijava/scijava-common/blob/3e0afe10014db09bd891c4290d994fbdf68f792f/src/main/java/org/scijava/io/location/LocationService.java).

The next steps I'd like you to try are:
- [ ] Add a `LocationService` to [OpenFile](https://github.com/scijava/scijava-plugins-commands/blob/af8646b5613faab4533588a00810ab859c75f125/src/main/java/org/scijava/plugins/commands/io/OpenFile.java).
- [ ] Use the `LocationService` to resolve the input `File`, instead of [forcing FileLocation](https://github.com/scijava/scijava-plugins-commands/blob/af8646b5613faab4533588a00810ab859c75f125/src/main/java/org/scijava/plugins/commands/io/OpenFile.java#L84).
- [ ] Pass the resulting resolved `Location` to the [IOService](https://github.com/scijava/scijava-common/blob/3e0afe10014db09bd891c4290d994fbdf68f792f/src/main/java/org/scijava/io/DefaultIOService.java#L86).
- [ ] Test again if this `OpenFile` change fixes `ExecuteCommands`

**Comment by ecmagnuson** [comment]
Ahhhhhh interesting, thanks, I will try this! 

I have a meeting and then class until 1:30 pm, and then I will get right on it :D

**Comment by hinerm** [comment]
After debugging, @ecmagnuson determined that switching to `LocationService` was sufficient to fix this issue! yay!

However - we noticed that in the [IOService, FileLocation is being manually constructed](https://github.com/scijava/scijava-common/blob/3e0afe10014db09bd891c4290d994fbdf68f792f/src/main/java/org/scijava/io/IOService.java#L72) - essentially bypassing the `Location` framework.

So as an *even better fix*, I would like you to:
- [ ] Update the `IOService#open(String)` to use a `LocationService` to resolve the string by default
- [ ] Test that this fixes the issue (with the **OLD** `OpenFile` command that *does not* use `LocationService` itself)

**Comment by ecmagnuson** [comment]
Just making, sure, but in your link above [IOService, FileLocation is being manually constructed](https://github.com/scijava/scijava-common/blob/3e0afe10014db09bd891c4290d994fbdf68f792f/src/main/java/org/scijava/io/IOService.java#L72) you have line 72 highlighted. We were looking at line 53 right before the meeting cut off, so was line 72 a hint towards creating a LocationService inside of IOService?

But line 72 is also using the same pattern of forcing a "new" FileLocation, so an additional thing that should be looked at?

**Comment by ctrueden** [comment]
@ecmagnuson I think both of those lines need to be fixed. One of them hardcodes `FileLocation` for opening, and the other for saving. Both should probably use the location resolving mechanism instead.

**Comment by ecmagnuson** [comment]
[Here](https://github.com/scijava/scijava-common/commit/9bcf5279c1d4b2e48649d9c59210996f21a65da2) is the branch I made for this. It passes all of the tests and the ExecuteCommand tutorial works now. Is this what you both had in mind?
