### ISSUE TITLE
Error no compatible inputs of type file found

### ISSUE THREAD

**Issue by kyralindley** [imagej/tutorials#105]
Hi, I am trying to use ImageJ to analyze tissue samples to see the percent positive of colour two from a IHC sample, here's my code, but the issue is I want to run it on a folder that has a lot of images to be analyzed and im currently getting this error "Error no compatible inputs pf type file found". How do i fix this please and thank you? 

```javascript
open("/Users/bowmanch/Library/CloudStorage/OneDrive-OregonHealth&ScienceUniversity/Data/20240517pmetIHC/Bioprints/Exported TIFFS");
run("Colour Deconvolution", "vectors=[H DAB]");
selectImage("pMETHPAFIIBioprint_1_1_1.tiff-(Colour_2)");
setAutoThreshold("Default dark no-reset");
//run("Threshold...");
setThreshold(0, 221, "raw");
//setThreshold(0, 221);
setOption("BlackBackground", true);
run("Convert to Mask");
run("Measure")
```

**Comment by ctrueden** [comment]
@kyralindley You can loop over all the images in the folder in a couple of different ways. Here is the ImageJ wiki article about it:

https://imagej.net/scripting/batch

I would recommend Option 2, the script template, which has a code skeleton in ImageJ macro you can fill in with your logic above (minus the `open` command).

In future, the best place to post questions like this is on https://forum.image.sc/ with tag `imagej`. (This repository is intended for development discussion and questions about the ImageJ2 tutorials, not original ImageJ macros.)

Hope it helps!

**Comment by kyralindley** [comment]
thank you !
