### ISSUE TITLE
Make christian stop complaining about our tutorials

### ISSUE THREAD

**Issue by hinerm** [imagej/tutorials#19]
make them look like this: https://github.com/biobv2015/knip-developer-guide

**Comment by dietzc** [comment]
actually, no. The tutorials are awesome. We just have to create a guide for someone who is new which brings them in a right order.

Ok. I volunteer to do that during the hackathon. Assign me.

**Comment by ctrueden** [comment]
The new tutorial notebooks (currently on the `beaker` branch, and merging to master imminently) have a defined and coherent order to them, with a top-level table of contents. Hopefully @dietzc is satisfied with this. If not, please reopen.
