### ISSUE TITLE
Incomplete "creating-services" project in dev-manual branch?

### ISSUE THREAD

**Issue by panovr** [imagej/tutorials#31]
It seems that the "creating-services" project in **dev-manual** branch is incomplete.

**Comment by ctrueden** [comment]
Indeed. You can see the progress in detail via the command:
```
git log dev-manual -- creating-services
```
Which says:
```
commit 49ea6ce46161c686f7e280314963a7838479970b
Author: etarena <arenaellen@gmail.com>
Date:   Wed Oct 14 14:59:25 2015 -0500

    WIP: creating services tutorial
```
The tutorial looks barely started, so don't worry about porting it to Beaker. We can leave this issue open for now until we decide whether to complete it, or just discard that commit.

**Comment by panovr** [comment]
Sure. I think maybe we need a wiki page to record the Beaker notebook porting status. 
@ctrueden May you create a bare-bone page in ImageJ wiki, then I can fill in the content?

**Comment by ctrueden** [comment]
> May you create a bare-bone page in ImageJ wiki, then I can fill in the content?

You can do it yourself.

However, why not just make a GitHub wiki page on imagej-tutorials? This particular page does not really need to be "user facing" right now.

**Comment by panovr** [comment]
I just created the wiki page, and I will fill in the contents.

**Comment by panovr** [comment]
I have added some contents in the wiki.
 @ctrueden Is this OK?

**Comment by ctrueden** [comment]
Wiki page looks fine. I am closing this issue since I have now actually deleted that `creating-services` tutorial stub.
