### ISSUE TITLE
Combine notebook tutorials with slideshows using RISE

### ISSUE THREAD

**Issue by imagejan** [imagej/tutorials#41]
The [RISE](https://github.com/damianavila/RISE) project brings [reveal.js](https://github.com/hakimel/reveal.js) presentations to Jupyter notebooks, i.e. allows live notebooks inside a full-fledged `reveal.js` presentation.

I quickly tested with the Scijava kernel, and there seem to be no issues. So let's create some educational presentation notebooks!

**Comment by imagejan** [comment]
Just noticed the announcement that [RISE is now running on binder](http://www.damian.oquanta.info/posts/rise-510-is-out.html). Does anybody have any experience with using https://mybinder.org/ ? @hadim @ctrueden: maybe we can get [SJJK](https://github.com/scijava/scijava-jupyter-kernel) running on binder.

**Comment by ctrueden** [comment]
Binder looks awesome, and makes the idea of using RISE much more compelling. You can link straight into the reveal.js-rendered version of the notebook on Binder.

I played for 10 minutes, and it is pretty great, but clearly still beta. For example, after making edits to cells... how do you revert to the original version of the code? I couldn't find a way. Hopefully these things will be ironed out over time.

**Comment by ctrueden** [comment]
I think we can get SJJK working in Binder by specifying a custom Dockerfile. Here is an [example of that for the Julia kernel](https://github.com/binder-project/example-dockerfile/blob/master/Dockerfile). Sorry I don't have time to try it myself right now.

**Comment by hadim** [comment]
Looks great. I'll try to investigate when I'll have some time.

**Comment by ctrueden** [comment]
Ha ha, it was easier than I thought: you can specify an `environment.yml` with the dependencies from conda! So I did it, and pushed to master, and now you can go to https://mybinder.org/ and type in `imagej/tutorials` and it will launch a live environment. SO GREAT

I included the RISE stuff so that you can play around with RISE in the live environment, too, if you want.

**Comment by ctrueden** [comment]
Not sure why I left this issue open. All works fine with RISE and Binder.
