### ISSUE TITLE
Maven IOException while reading renjin-core-0.8.1906.jar

### ISSUE THREAD

**Issue by DavidGauntt** [imagej/tutorials#43]
I have not been able to build any of the tutorial projects.  If I right-click on a pom.xml file (e.g. from add-rois) and select "Maven build", "Maven install", "Maven generate sources", etc, the action fails with the following error messages in the Console:

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-rules) @ add-rois ---
[WARNING] Rule 5: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
IOException while reading /Users/dgauntt/.m2/repository/org/renjin/renjin-core/0.8.1906/renjin-core-0.8.1906.jar
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project add-rois: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

I have set permissions as "Read/Write for Everyone" along the full path from .m2 down to renjin-core-0.8.1906.jar, but that did not work.  The file renjin-core-0.8.1906.jar is at the path specified.

I am running Eclipse Oxygen 1 with Maven m2e installed on a Mac running El Capitan 10.11.6.  I am new to Maven

**Comment by ctrueden** [comment]
Sometimes pieces of the local repository cache (`$HOME/.m2/repository`) do not get populated properly—e.g., when there is a transient network issue. Maybe the `renjin-core-0.8.1906.jar` got corrupted during download? Can you try to execute `rm -rf $HOME/.m2/repository/org/renjin` and rerun the build with the `-U` flag?

**Comment by DavidGauntt** [comment]
Thank you!  That worked.  After deleting the renjin folder, I ran a “generate-sources”, and Maven downloaded the rennin folder.
—
David M. Gauntt, Ph.D.
Associate Professor, Department of Radiology
UAB Medical Center
