### ISSUE TITLE
Updating choices of widgets has no effect

### ISSUE THREAD

**Issue by Meyenhofer** [imagej/tutorials#50]
in 
https://github.com/imagej/tutorials/blob/master/maven-projects/dynamic-commands/src/main/java/DynamicCallbacks.java
setting new choices for a widget does not have any effect. The widget does not seem to be updates. 
(MacOS 10.13.3)

**Comment by imagejan** [comment]
Hm, did you see the comment:

https://github.com/imagej/tutorials/blob/11bc376ed81b43c6abf984c6ca7740aaea62c8aa/maven-projects/dynamic-commands/src/main/java/DynamicCallbacks.java#L29-L31

I'm not sure what the current status of this is...

**Comment by Meyenhofer** [comment]
Nope, did not see this. It's pretty clear though...

**Comment by imagejan** [comment]
For the record, here's some related discussion on the forum:
[ImageJ2 Command - callback function for persisted Parameters](http://forum.imagej.net/t/imagej2-command-callback-function-for-persisted-parameters/6663/9?u=imagejan)

**Comment by ctrueden** [comment]
> I'm not sure what the current status of this is...

We can try to make this better as part of the SciJava 3 widget system redesign.
